language: node_js
dist: xenial
node_js:
  - '8'
  - '10'

branches:
  only:
    - master  # (PRs to master, master merges, master pushes)

script:
  - npm install
  - lerna bootstrap
  - npm -C ./packages/usage run start
